// Canonical token source for the design system.
// Single source of truth. Edit here, then run `npm run build` to regenerate
// dist/tokens.css and dist/preset.css. Values come from the reference spec
// (foundations/light.md, foundations/dark.md, backgrounds.md).

// Material-Design-3 color roles, per theme. Theme-swapping is handled by the
// generated [data-theme] selector, so consumers use one semantic name everywhere.
export const colors = {
  light: {
    surface: "#faf9f7",
    "surface-dim": "#dadad8",
    "surface-bright": "#faf9f7",
    "surface-container-lowest": "#ffffff",
    "surface-container-low": "#f4f3f1",
    "surface-container": "#efeeec",
    "surface-container-high": "#e9e8e6",
    "surface-container-highest": "#e3e2e0",
    "surface-variant": "#e3e2e0",
    "on-surface": "#1a1c1b",
    "on-surface-variant": "#444748",
    "inverse-surface": "#2f3130",
    "inverse-on-surface": "#f1f1ef",
    outline: "#747878",
    "outline-variant": "#c4c7c7",
    "surface-tint": "#5f5e5e",
    primary: "#000000",
    "on-primary": "#ffffff",
    "primary-container": "#1c1b1b",
    "on-primary-container": "#858383",
    "inverse-primary": "#c8c6c5",
    secondary: "#5e5e5e",
    "on-secondary": "#ffffff",
    "secondary-container": "#e1dfdf",
    "on-secondary-container": "#626263",
    tertiary: "#000000",
    "on-tertiary": "#ffffff",
    "tertiary-container": "#1b1c19",
    "on-tertiary-container": "#848480",
    background: "#faf9f7",
    "on-background": "#1a1c1b",
    // Semantic state colors (fixed meaning across the system).
    error: "#ba1a1a",
    "on-error": "#ffffff",
    "error-container": "#ffdad6",
    "on-error-container": "#93000a",
    success: "#2e7d52",
    "success-container": "#e4f0e9",
    warning: "#9a6b12",
    "warning-container": "#f3ecdc",
    info: "#2f5fcf",
    "info-container": "#e3e9f7",
  },
  dark: {
    surface: "#141313",
    "surface-dim": "#141313",
    "surface-bright": "#3a3939",
    "surface-container-lowest": "#0e0e0e",
    "surface-container-low": "#1c1b1b",
    "surface-container": "#201f1f",
    "surface-container-high": "#2a2a2a",
    "surface-container-highest": "#353434",
    "surface-variant": "#353434",
    "on-surface": "#e5e2e1",
    "on-surface-variant": "#c4c7c8",
    "inverse-surface": "#e5e2e1",
    "inverse-on-surface": "#313030",
    outline: "#8e9192",
    "outline-variant": "#444748",
    "surface-tint": "#c6c6c7",
    primary: "#ffffff",
    "on-primary": "#2f3131",
    "primary-container": "#e2e2e2",
    "on-primary-container": "#636565",
    "inverse-primary": "#5d5f5f",
    secondary: "#c6c6cb",
    "on-secondary": "#2f3034",
    "secondary-container": "#46464b",
    "on-secondary-container": "#b5b4ba",
    tertiary: "#ffffff",
    "on-tertiary": "#2f3131",
    "tertiary-container": "#e2e2e2",
    "on-tertiary-container": "#636565",
    background: "#141313",
    "on-background": "#e5e2e1",
    error: "#ffb4ab",
    "on-error": "#690005",
    "error-container": "#93000a",
    "on-error-container": "#ffdad6",
    success: "#5fbd88",
    "success-container": "#1e2f26",
    warning: "#d9ae55",
    "warning-container": "#322a1a",
    info: "#7fa6e8",
    "info-container": "#1b2536",
  },
};

// Theme-specific non-color tokens: glass, ambient shadow, aurora gradient stops
// (no photo layer, per the locked decision).
export const themeVars = {
  light: {
    "glass-fill": "rgba(255, 255, 255, 0.60)",
    "glass-border": "rgba(255, 255, 255, 0.60)",
    "glass-blur": "32px",
    "ambient-shadow": "0 0 40px rgba(26, 26, 26, 0.05)",
    "aurora-1": "rgba(220, 210, 200, 0.40)",
    "aurora-2": "rgba(200, 215, 205, 0.40)",
    "aurora-3": "rgba(215, 205, 195, 0.30)",
    "grain-blend": "overlay",
  },
  dark: {
    "glass-fill": "rgba(28, 26, 22, 0.50)",
    "glass-border": "rgba(255, 255, 255, 0.09)",
    "glass-blur": "32px",
    "ambient-shadow": "0 20px 50px rgba(0, 0, 0, 0.45)",
    "aurora-1": "rgba(76, 58, 81, 0.40)",
    "aurora-2": "rgba(45, 60, 50, 0.40)",
    "aurora-3": "rgba(80, 65, 40, 0.30)",
    "grain-blend": "overlay",
  },
};

// Theme-invariant tokens. Emitted once in :root.
export const shared = {
  font: {
    display: "'Bodoni Moda', Georgia, 'Times New Roman', serif",
    body: "'Inter', system-ui, -apple-system, sans-serif",
    label: "'Inter', system-ui, -apple-system, sans-serif",
    mono: "'Geist Mono', ui-monospace, monospace",
  },
  // Type scale. Display uses clamp() to reconcile the light (72px) and dark
  // (120px) display sizes into one responsive token. Sizes in rem.
  text: {
    "display-size": "clamp(2.75rem, 5vw + 1.5rem, 7.5rem)",
    "display-lh": "1.05",
    "display-tracking": "-0.02em",
    "display-weight": "700",
    "headline-lg-size": "clamp(2rem, 2.5vw + 1rem, 3rem)",
    "headline-lg-lh": "1.1",
    "headline-lg-tracking": "-0.01em",
    "headline-lg-weight": "600",
    "headline-md-size": "2rem",
    "headline-md-lh": "1.25",
    "headline-md-weight": "500",
    "body-lg-size": "1.125rem",
    "body-lg-lh": "1.6",
    "body-md-size": "1rem",
    "body-md-lh": "1.5",
    "body-sm-size": "0.875rem",
    "body-sm-lh": "1.5",
    "label-md-size": "0.75rem",
    "label-md-lh": "1.33",
    "label-md-tracking": "0.08em",
    "label-md-weight": "600",
    "label-sm-size": "0.6875rem",
    "label-sm-lh": "1.27",
    "label-sm-tracking": "0.05em",
    "label-sm-weight": "500",
    "label-caps-tracking": "0.2em",
  },
  space: {
    unit: "0.25rem",
    "container-max": "75rem",
    gutter: "2rem",
    "margin-desktop": "4rem",
    "margin-mobile": "1.25rem",
    "section-gap": "7.5rem",
    "card-padding": "2rem",
    "stack-sm": "0.5rem",
    "stack-md": "1.5rem",
  },
  radius: {
    DEFAULT: "0",
    sharp: "0",
    soft: "0.25rem",
    full: "9999px",
  },
  motion: {
    ease: "cubic-bezier(0.22, 1, 0.36, 1)",
    "dur-micro": "0.18s",
    "dur-theme": "0.6s",
  },
};

export const fonts = [
  "Bodoni+Moda:ital,opsz,wght@0,6..96,400..900;1,6..96,400..900",
  "Inter:wght@400;500;600;700",
];
