// Generates dist/tokens.css (CSS variables, light + dark) and dist/preset.css
// (Tailwind v4 @theme mapping) from the canonical token source.
import { writeFileSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import { colors, themeVars, shared, fonts } from "../tokens/tokens.mjs";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const dist = resolve(root, "dist");
mkdirSync(dist, { recursive: true });

const line = (name, value) => `  --${name}: ${value};`;

function sharedVars() {
  const out = [];
  for (const [k, v] of Object.entries(shared.font)) out.push(line(`font-${k}`, v));
  for (const [k, v] of Object.entries(shared.text)) out.push(line(`text-${k}`, v));
  for (const [k, v] of Object.entries(shared.space)) out.push(line(`space-${k}`, v));
  for (const [k, v] of Object.entries(shared.radius))
    out.push(line(k === "DEFAULT" ? "radius" : `radius-${k}`, v));
  for (const [k, v] of Object.entries(shared.motion)) out.push(line(k, v));
  return out.join("\n");
}

function block(selector, ...maps) {
  const body = maps
    .flatMap((m) => Object.entries(m).map(([k, v]) => line(k, v)))
    .join("\n");
  return `${selector} {\n${body}\n}`;
}

// tokens.css: :root = light + all theme-invariant tokens; [data-theme=dark] = dark.
const tokensCss = `/* GENERATED by scripts/build-tokens.mjs. Do not edit by hand. */
:root {
${[
  ...Object.entries(colors.light).map(([k, v]) => line(k, v)),
  ...Object.entries(themeVars.light).map(([k, v]) => line(k, v)),
].join("\n")}
${sharedVars()}
}

[data-theme="dark"] {
${[
  ...Object.entries(colors.dark).map(([k, v]) => line(k, v)),
  ...Object.entries(themeVars.dark).map(([k, v]) => line(k, v)),
].join("\n")}
}
`;

// preset.css: maps semantic vars to Tailwind v4 theme namespaces so utilities
// like bg-surface / text-on-surface / font-display / gap-section-gap exist.
// `inline` keeps utilities pointing at the runtime var, so [data-theme] swaps work.
const colorTheme = Object.keys(colors.light)
  .map((k) => `  --color-${k}: var(--${k});`)
  .join("\n");

const fontTheme = [
  "  --font-display: var(--font-display);",
  "  --font-body: var(--font-body);",
  "  --font-sans: var(--font-body);",
  "  --font-mono: var(--font-mono);",
].join("\n");

const spacingKeys = [
  "gutter",
  "margin-desktop",
  "margin-mobile",
  "section-gap",
  "card-padding",
  "stack-sm",
  "stack-md",
];
const spacingTheme = [
  "  --spacing: var(--space-unit);",
  ...spacingKeys.map((k) => `  --spacing-${k}: var(--space-${k});`),
].join("\n");

const radiusTheme = [
  "  --radius-soft: var(--radius-soft);",
  "  --radius-full: var(--radius-full);",
].join("\n");

const presetCss = `/* GENERATED by scripts/build-tokens.mjs. Do not edit by hand. */
@import "./tokens.css";

@theme inline {
${colorTheme}
${fontTheme}
${spacingTheme}
${radiusTheme}
}
`;

// fonts.css: Google Fonts for the base pair.
const fontsCss = `/* GENERATED by scripts/build-tokens.mjs. Do not edit by hand. */
@import url("https://fonts.googleapis.com/css2?${fonts
  .map((f) => `family=${f}`)
  .join("&")}&display=swap");
`;

writeFileSync(resolve(dist, "tokens.css"), tokensCss);
writeFileSync(resolve(dist, "preset.css"), presetCss);
writeFileSync(resolve(dist, "fonts.css"), fontsCss);

console.log("Built dist/tokens.css, dist/preset.css, dist/fonts.css");
